<div>
    <h4>Hubspot Import</h4>
    <table>
        <thead>
        <tr>
            <th>Current Step:</th>
            <td id="step"></td>
        </tr>
        <tr>
            <th>Total:</th>
            <td id="total"></td>
        </tr>
       <tr>
           <th> Progress</th>
           <td style="width:1000px"><div id="progressbar"></div></td>
       </tr>
        <tr>
            <th>Log</th>
            <td id="log"></td>
        </tr>
        </thead>
    </table>
</div>
