<style>
    .currency:before {
        content: "$";
    }

    .revenuePositive {
        color: green;
    }

    .revenueNegative {
        color: red;
        font-weight: bold;
    }

    .revenueData {
        min-height: 180px;
    }
    .tabs-login{
        background-color:#498667;
        color:#fff;

    }
    .tabs-login h2{
        color:#fff;
        margin: .75em auto;
        text-align:center;

    }
    .tab-content div{
        padding:0px 20px;
    }

</style>
<?php include_once(__DIR__.'/../base/page_navigation.phtml');?>
<div class="container">

      <?php  include_once(__DIR__.'/../base/page_header.phtml');?>


    <div class="login-body">
        <article class="container-login center-block">
            <section>

                <div class="tab-content tabs-login col-lg-12 col-md-12 col-sm-12 cols-xs-12">
                    <div id="login-access" class="tab-pane fade active in">
                        <h2>Advertiser Log In</h2>
                        <form method="post" action="<?php echo WEB_ROOT;?>login" accept-charset="utf-8" autocomplete="off" role="form" class="form-horizontal">
                            <div class="form-group ">
                                <label for="login" class="sr-only">Email</label>
                                <input type="text" class="form-control" name="username" id="login_value"
                                       placeholder="Email" tabindex="1" value="<?php echo @$this->_request['username'];?>" />
                            </div>
                            <div class="form-group ">
                                <label for="password" class="sr-only">Password</label>
                                <input type="password" class="form-control" name="password" id="password"
                                       placeholder="Password" value="" tabindex="2" />
                            </div>
<!--                            <div class="checkbox">-->
<!--                                <label class="control-label" for="remember_me">-->
<!--                                    <input type="checkbox" name="remember_me" id="remember_me" value="1" class="" tabindex="3" /> Remember Me-->
<!--                                </label>-->
<!--                            </div>-->
                            <br/>
                            <div class="form-group ">
                               <center> <button type="submit" name="log-me-in" id="submit" tabindex="5" class="btn btn-lg btn-primary">Submit</button></center>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </article>
    </div>
    </div>

</div>
<script>
    function delete_cookie( name ) {
        document.cookie = name + '=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';
    }
    delete_cookie('advertiser');
</script>

<?php require_once(__DIR__.'/../base/page_footer.phtml');?>