
<div class="login-body">
    <article class="container-login center-block">
        <section>
            <div class="tab-content tabs-login col-lg-4 col-md-6 col-sm-10 cols-xs-12 center-block" style="margin:auto;">
                <div id="login-access" class=" ">
                    <h2><?php echo APPLICATION ?> Password Recover</h2>
                    A password recovery link has been sent to <?php echo $email;?>.
                </div>
            </div>
        </section>
    </article>
</div>
