<div class="login-body">
    <article class="container-login center-block">
        <section>
            <div class="tab-content tabs-login col-lg-4 col-md-6 col-sm-10 cols-xs-12 center-block"
                 style="margin:auto;">
                <div id="login-access" class=" ">
                    <h2><?php echo APPLICATION ?> Password Reset</h2>
                    <form method="post" action="<?php echo WEB_ROOT; ?>login/reset" accept-charset="utf-8" autocomplete="off"
                          role="form" id="form" class="form-horizontal">
                        <div class="form-group ">
                            <label for="login" class="sr-only">Username/Email</label>
                            <input type="text" class="form-control" name="email" id="email"
                                   placeholder="Email" tabindex="1" value=""/>
                            <input type="hidden" name="hash" value="<?php echo $hash; ?>" />
                        </div>
                        <div class="form-group ">
                            <label for="password" class="sr-only">Password</label>
                            <input type="password" class="form-control" name="password" id="password"
                                   placeholder="Password" value="" tabindex="2"/>
                        </div>
                        <div class="form-group ">
                            <label for="password" class="sr-only">ConfirmPassword</label>
                            <input type="password" class="form-control" name="password2" id="password2"
                                   placeholder="Verify Password" value="" tabindex="2"/>
                        </div>
                        <ul>
                            <li>The password must contain at least 1 lowercase alphabetical character</li>
                            <li>The password must contain at least 1 uppercase alphabetical character</li>
                            <li>The password must contain at least 1 numeric character</li>
                            <li>The password must contain at least one special character [!@#$%^&]</li>
                            <li>The password must be eight characters or longer</li>
                        </ul>
                        <br/>
                        <div class="form-group ">
                            <center>
                                <span name="log-me-in" id="submit" tabindex="5" class="btn btn-lg btn-primary">
                                    Submit
                                </span>
                            </center>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </article>
</div>
<script>
    var strongRegex = new RegExp("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,})");
    $(document).on('click', '#submit', function () {
        $('#page_notices').html("").removeClass('ui-state-error');
        if(!strongRegex.test($('#password').val())){
            $('#page_notices').html("The supplied password does not meeet the requirement criteria").addClass('ui-state-error');
        }else {
            if ($('#password').val() != $('#password2').val()) {
                $('#page_notices').html("The supplied passwords do not match").addClass('ui-state-error');
            } else {
                if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test($('#email').val())) {
                    $('#form').submit();
                } else {
                    $('#page_notices').html("The supplied email appears invalid").addClass('ui-state-error');
                }
            }
        }
    })
</script>
