<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description"
      content="Freely usable API services, DNS Lookup, RDNS, Earthquake, Rainbow Text, WhoAmI, My IP, and much more">
<meta name="keywords"
      content="earthquake, fatherstorm, USGS, api, tools, info, richter, quake, DNS, RDNS, WhoAmI, What Is My IP,IP, Hostname, userAgent, IRC, Weather">
<link href="http://api.fatherstorm.com/api_favicon.ico" rel="icon" type="image/x-icon"/>
<title>FatherStorm's API Documentation</title>
<meta name="environment" content="<?php echo ENVIRONMENT; ?>">
<meta name="environment" content="<?php echo ENVIRONMENT; ?>">
<meta name="file" content="<?php echo __FILE__; ?>">
<meta name="author" content="">
<link rel="icon" href="/favicon.ico">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
<title><?php echo $this->registry->get('title'); ?></title>
<!-- MDB icon -->
<link rel="icon" href="/img/mdb-favicon.ico" type="image/x-icon">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="/css/bootstrap.min.css">
<!-- Material Design Bootstrap -->
<link rel="stylesheet" href="/css/mdb.min.css">
<!-- Your custom styles (optional) -->
<link rel="stylesheet" href="/css/style.css">
<script type="text/javascript" src="//unpkg.com/axios/dist/axios.min.js"></script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

<![endif]-->
<?php
foreach ($this->css as $file) {
   echo sprintf(' <link href="%s%s" rel="stylesheet">', WEB_ROOT, $file);
}
?>
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>

<script type="text/javascript" src="/js/jquery.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="/js/popper.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="/js/bootstrap.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="/js/mdb.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="/js/jquery.timeago.js" type="text/javascript"></script>
<script src="/js/notify.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css"/>
<!--    <link rel="stylesheet" href="--><?php //echo WEB_ROOT;?><!--css/jquery.dynatable.css"/>-->
<!--    <script src="--><?php //echo WEB_ROOT;?><!--js/jquery.dynatable.js"></script>-->
<script>
    $(document).on('click', '.getDocumentation', function () {
        var url = WEB_ROOT + 'reports/ajax/do/getDocumentation';
        $.ajax({
            url: url,
            success: function (data) {
                <?php if($this->documentationMethod == 'jsPDF'){ ?>

                var doc = new jsPDF()
                doc.fromHTML(data.data, 10, 10, {width: 160})
                doc.save('API_Documentation.pdf')
                <?php }else{ ?>
                var div = $('<div/>');
                $(div).html(data.data);
                $(div).dialog({width: '90%', title: 'API Documentation'});
                <?php } ?>
            }
            , dataType: "json"
        });
    });
</script>
<?php
foreach ($this->js as $file) {
    echo sprintf('<script src="%s?%s"></script>', WEB_ROOT . $file, microtime(true));
}
?>

